base_config: common.yaml

data:
  split_file: splits_deeplab_ft.json
  id_based_test_ratio: 0.1
  image_size: [384, 384]

model:
  name: deeplabv3plus_smp
  encoder_name: tu-mobilenetv3_large_100
  encoder_weights: imagenet
  encoder_output_stride: 16
  decoder_channels: 256
  dropout: 0.1
  freeze_backbone: false

training:
  epochs: 60
  batch_size: 20
  lr: 0.00003
  scheduler:
    name: cosine
    warmup_epochs: 0
    eta_min: 0.000001
  early_stopping:
    enabled: true
    patience: 8
    min_delta: 0.0
